plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

tasks.named('processTestResources') {
    // Для тестовых ресурсов - не выбрасывать ошибку, а просто игнорировать дубли
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('processResources') {
    // Для обычных ресурсов можно тоже настроить
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
sourceSets {
    test {
        resources {
            srcDir 'src/test/resources'
        }
    }
}

dependencies {
    // JUnit 5
    implementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.2'


    //AssertsJ
    testImplementation 'org.assertj:assertj-core:3.24.2'

    // Allure
    implementation group: 'io.qameta.allure', name: 'allure-junit5', version: '2.29.0'

    //Selenide
    implementation group: 'com.codeborne', name: 'selenide', version: '7.5.1'

}

test {
    useJUnitPlatform()
}
